name: picka
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  webview_flutter: ^3.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8
  url_launcher: ^6.1.5

flutter_icons:

  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

 
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash.png  


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
